#spring.application.name=flight_booking_server

server:
  port: 8080
  servlet:
    context-path: /flight_booking

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/flight_booking_db"
    username: root
    password: root

jwt:
  secret: DLriNDSk32LjFMR0z46IrURtjCGtcID0BOcy5ikilBe9JbmXkFAQkO/pO2/aul12
  expiration: 86400000
